
#Усі налаштування основного ігрового процесу
[gameplay]
	#Чи генерувати кораблі/табори постачання в скринях з лутом. [За замовчуванням: true]
	generatesupplyloot = true

#Усі налаштування системи запитів
[requestsystem]
	#Чи повинна система запитів показувати інформацію налагодження в debug.log? корисно у разі несправності. [За замовчуванням: false]
	enabledebuglogging = false

